betkiray/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from gofor.views import gofor_detail
from core.views import home, about, contact, signup, search, tekeray
from landlord.views import akeray_detail, add_akeray, delete_akeray, update_akeray
from django.contrib.auth import views
from landlord.api import api_add_to_gofor, api_remove_from_gofor, api_add_new_rent


urlpatterns = [
    path('', home, name = 'home'),
    path('search/', search, name = 'search'),
    path('tekeray/', tekeray, name = 'tekeray'),
    path('about/', about, name='about'),
    path('contact/', contact, name = 'contact'),
    path('gofor/', gofor_detail, name = 'gofor'),
    path('add/', add_akeray, name='add_akeray'),
    path('admin/', admin.site.urls),

    #Auth
    path('signup/', signup, name = 'signup'),
    path('logout/', views.LogoutView.as_view(), name = 'logout'),
    path('login/', views.LoginView.as_view(), name = 'login'),

    # API
    path('add_to_gofor/', api_add_to_gofor, name = 'api_add_to_gofor'),    
    path('remove_from_gofor/', api_remove_from_gofor, name = 'api_remove_from_gofor'),  
    path('add_new_rent/', api_add_new_rent, name = 'api_add_new_rent'),


    # Landlord
    path('<int:id>/', akeray_detail, name='akeray_detail'),
    path('<akeray_id>/update', update_akeray, name='update'),
    path('<akeray_id>/delete', delete_akeray, name='delete'),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

landlord/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Akeray(models.Model):

    RENTED = 'rented'
    AVAILABLE = 'available'

    STATUS_CHOICE = (
        (RENTED, 'Rented'),
        (AVAILABLE, 'Available')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200, null=True, blank=True)
    subcity = models.CharField(max_length=200, null=True, blank=True)
    kebele = models.CharField(max_length=20, null=True, blank=True)
    price = models.IntegerField()
    summary = models.TextField(blank=True , null=True)
    phone = models.CharField(max_length=20)
    image = models.ImageField(upload_to='uploads', blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default=AVAILABLE)

   
    def __str__(self):
        return '%s' % self.title 

    class Meta:
        verbose_name_plural = 'Akeray'
        ordering = ['-date_added']

User.akeray = property(lambda u:Akeray.objects.get_or_create(user=u)[0])
    
class AkerayImage(models.Model):
    akeray = models.ForeignKey(Akeray, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads', blank=True, null=True)

    def __str__(self):
        return '%s' % self.akeray.title

    class Meta:
        verbose_name_plural = 'Images'

landlord/forms.py
from django import forms

from .models import Akeray, AkerayImage

# Create your forms here 

class AkerayForm(forms.ModelForm):
    class Meta:
        model = Akeray
        fields = ('image', 'title', 'location', 'subcity', 'kebele', 'price', 'summary', 'phone')

class ImageForm(forms.ModelForm):
    image = forms.ImageField(
        label="image",
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )
    class Meta:
        model = AkerayImage
        fields = ("image",)

landlord/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from .models import Akeray, AkerayImage
from .forms import AkerayForm, ImageForm

# Create your views here.
def akeray_detail(request, id):

    akeray = get_object_or_404(Akeray, pk=id)

    imagesstring = "{ 'image': '%s' }," % (akeray.image.url)

    for image in akeray.images.all():
        imagesstring = imagesstring + ("{ 'image': '%s' }," % (image.image.url))

    return render(request, 'akeray_detail.html', context={'akeray': akeray, 'imagesstring': imagesstring})

@login_required
def add_akeray(request):
    if request.method == 'POST':

        form = AkerayForm(request.POST, request.FILES)
        files = request.FILES.getlist("image", request.user)
    
        if form.is_valid():
            f=form.save(commit=False)
            f.user = request.user
            f.save()

            for i in files:
                AkerayImage.objects.create(akeray=f, image=i)
            messages.success(request, "New rent added!")

            return HttpResponseRedirect("/tekeray")

        else:
            return (form.errors)

    else:
        form = AkerayForm()
        imageform = ImageForm()

    
        context = {
            'form': form,
            'imageform': imageform
        }
    return render(request, 'add_akeray.html', context)

@login_required
def update_akeray(request, akeray_id):
    akeray = get_object_or_404(Akeray, id=akeray_id)

    files = request.FILES.getlist("image")

    form = AkerayForm(request.POST or None, instance=akeray)

    if form.is_valid():
        f=form.save(commit=False)
        f.user == request.user
        f.save()
       
        for i in files:
            AkerayImage.objects.create(akeray=f, image=i)
        messages.success(request, "New rent added!")

        
        return HttpResponseRedirect("/")

    else:
        form = AkerayForm()
        imageform = ImageForm()
    
    context = {
        'form': form,
        'imageform': imageform
    }

    return render(request, 'update_akeray.html', context)




@login_required
def delete_akeray(request, akeray_id):
    akeray = get_object_or_404(Akeray, id = akeray_id)

    if request.user == akeray.user:

        Akeray.objects.filter(id=akeray_id).delete()
        return HttpResponseRedirect("/tekeray") 

    return render(request, "delete_akeray.html", {'akeray': akeray})

landlord/templates/add_akeray.html
{% extends 'base.html' %}
{% block title %} add | {% endblock %}
{% block content %}
        
    {% if request.user.is_authenticated %} 
        <div class="columns">
            <div class="column is-6 is-offset-3">
                <form method="post" enctype="multipart/form-data" action=".">

                    {% csrf_token %}
        
                    <input type="hidden" name="next" value="{{ next }}">
        
                    <div class="field">
                        <label>House Type</label>
                        <div class="control">
                            <input type="text" class="input" name="title" id="id_title" placeholder="e.g., apartment, condominum, villa or one room rentals, etc..">
                        </div>
                    </div>
                    <div class="field">
                        <label>City</label>
                        <div class="control">
                            <input type="text" class="input" name="location" id="id_location">
                        </div>
                    </div>
                    <div class="field">
                        <label>K/ketema</label>
                        <div class="control">
                            <input type="text" class="input" name="subcity" id="id_subcity">
                        </div>
                    </div>
                    <div class="field">
                        <label>Kebele</label>
                        <div class="control">
                            <input type="text" class="input" name="kebele" id="id_kebele">
                        </div>
                    </div>
                    <div class="field">
                        <label>Price/month</label>
                        <div class="control">
                            <input type="number" class="number" name="price" id="id_price">
                        </div>
                    </div>
                    <div class="control">
                        <label>Description</label>       
                            <textarea name="summary" id="id_summary" class="textarea" cols="30" rows="10" 
                            placeholder="e.g., Number of bed room, room size, 
        includes electricity and water, 
        room floor with ceramic tile, 
        include wifi, etc.."></textarea>       
                    </div>
                    <div class="field">
                        <label>Contact</label>
                        <div class="control">
                            <input type="text" class="input" name="phone" id="id_title" placeholder="phone number">
                        </div>
                    </div>
                    
                    {% if form.erros %}
                        <div class="notification is-danger">
                            <p>Something went worng!</p>
                        </div>
                    {% endif %}
        
                    <p style="font-size: 12px">Choose multiple pictures</p>
                    {{ imageform.management_form }}
                    {% for form in imageform %}
                        {{ form }}
                    {% endfor %} 
                    <input type="submit" name="submit" value="Post for Rent" class="button is-success" />
                </form>
            </div>
        </div>
    {% else %}
        <a href="{% url 'login' %}">login</a>or <a href="{% url 'signup' %}">signup</a>
    {% endif %}

{% endblock %}

{% block scripts %}
    <script>
        var addakerayapp = new Vue({
            el: ('#addakerayapp'),
            delimiters: ['[[', ']]'],
            data() {
                return {
                    title: '',
                    location: '',
                    subcity: '',
                    kebele: '',
                    price: '',
                    summary: '',
                    phone: '' ,
                    date_added: 'Now'        
                }
            },
            methods: {
                submitForm() {
                    console.log('submit')

                    const data = {
                        'title': this.title,
                        'location': this.location,
                        'subcity': this.subcity,
                        'kebele': this.kebele,
                        'price': this.price,
                        'summary': this.summary,
                        'phone': this.phone,
                        'date_added': this.date_added
                    }
    
                    fetch('/add_new_rent/', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify(data)
                    })
                    .then((response) => {
                        console.log(response)
                        
    
                    })
                    .catch(function (error) {
                        console.log(error)
                    })
                }
            }

        })
    </script>
{% endblock %}

landlord/templates/akeray_detail.html
{% extends 'base.html' %}
{% block title %} {{ akeray.title }} | {% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
       <div id="akerayapp">
            <img :src="mainImage">
            <br>
            <div class="columns">
                <div class="column is-2" v-for="image in images">
                    <figure class="image is-128x128">
                        <img :src="image.image" @click="changeMainImage(image.image)">
                    </figure>
                </div>
            </div>
            <h1 class="title">{{ akeray.title }}</h1>
            <h2 class="subtitle">{{ akeray.price }} birr/month</h2>
            <p><strong>City: </strong>{{ akeray.location }}</p>
            <p><strong>K/ketema: </strong>{{ akeray.subcity }}</p>
            <p><strong>Kebele: </strong>{{ akeray.kebele }}</p>
            <p><strong>More info: </strong>{{ akeray.summary }}</p>
            <p><strong><i class="fas fa-phone"></i></strong> {{ akeray.phone }}</p>
                                    
            <br>
            <button @click="addToGofor({{akeray.id}})" class="button is-success">Save to Favourites</button>
       </div>
    {% else %}
       <div class="field">
        <div class="control">
            <center class="center"><p>You need to <a href="{% url 'login' %}">Login</a> Or <a href="{% url 'signup' %}">Signup</a> to proceed</p></center>
        </div>
       </div>
    {% endif %}
    
{% endblock %}

{% block scripts %}
<script>
    var akerayapp = new Vue({
        el: ('#akerayapp'),
        delimiters: ['[[', ']]'],
        data() {
            return {
                mainImage: '{{ akeray.image.url }}',
                images: [{{ imagesstring|safe }}]
            }
        },
        methods: {
            changeMainImage(image) {
                this.mainImage = image;
            },
            addToGofor(akeray_id) {
                console.log('akeray_id:', akeray_id)
                alert('Check your favourite to see your saves!')

                var data = {'akeray_id': akeray_id, 'update': false, 'quantity': 1}

                fetch('/add_to_gofor/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    credentials: 'same-origin',
                    body: JSON.stringify(data)
                })
                .then((response) => {
                    console.log(response)

                })
                .catch(function (error) {
                    console.log(error)
                })
            }
        }
    })
</script>
{% endblock %}

landlord/templates/category_detail.html
{% extends 'base.html' %}
{% block title %} {{ category.title }} | {% endblock %}
{% block content %}
    <h1 class="title">Home</h1>
    <div class="columns is-multiline">
        {% for akeray in akerays %}
            <div class="column is-4">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <h2 class="subtitle">{{ akeray.title }}</h2>
                                <p>{{ akeray.price }} birr/month</p>
                            </div>
                        </div>
                     
                    <footer class="card-footer">
                        <a href="{% url 'akeray_detail' category.slug akeray.slug %}" class="card-footer-item">View</a>
                    </footer>
                </div>
            </div>
        {% endfor %}
    </div>
   
{% endblock %}

landlord/templates/delete_akeray.html
{% extends 'base.html' %}
{% block title %} contact | {% endblock %}
{% block content %}

    <div class="navbar-item">
        <div class="notification is-danger is-offset-3">
            <p>You are not authorized to delete this item!</p>
        </div>
       
    </div>

   
{% endblock %}

landlord/templates/update_akeray.html
{% extends 'base.html' %}
{% block title %} update {% endblock %}
{% block content %}
        
    {% if request.user.is_authenticated %} 
        <div class="columns">
            <div class="column is-6 is-offset-3">
                <form method="post" enctype="multipart/form-data" action=".">

                    {% csrf_token %}
        
                    <input type="hidden" name="next" value="{{ next }}">
        
                    <div class="field">
                        <label>House Type</label>
                        <div class="control">
                            <input type="text" class="input" name="title" id="id_title" placeholder="e.g., apartment, condominum, villa or one room rentals, etc..">
                        </div>
                    </div>
                    <div class="field">
                        <label>City</label>
                        <div class="control">
                            <input type="text" class="input" name="location" id="id_location">
                        </div>
                    </div>
                    <div class="field">
                        <label>K/ketema</label>
                        <div class="control">
                            <input type="text" class="input" name="subcity" id="id_subcity">
                        </div>
                    </div>
                    <div class="field">
                        <label>Kebele</label>
                        <div class="control">
                            <input type="text" class="input" name="kebele" id="id_kebele">
                        </div>
                    </div>
                    <div class="field">
                        <label>Price/month</label>
                        <div class="control">
                            <input type="number" class="number" name="price" id="id_price">
                        </div>
                    </div>
                    <div class="control">
                        <label>Description</label>       
                            <textarea name="summary" id="id_summary" class="textarea" cols="30" rows="10" 
                            placeholder="e.g., Number of bed room, room size, 
        includes electricity and water, 
        room floor with ceramic tile, 
        include wifi, etc.."></textarea>       
                    </div>
                    <div class="field">
                        <label>Contact</label>
                        <div class="control">
                            <input type="text" class="input" name="phone" id="id_title" placeholder="phone number">
                        </div>
                    </div>
                    
                    {% if form.erros %}
                        <div class="notification is-danger">
                            <p>Something went worng!</p>
                        </div>
                    {% endif %}
        
                    <p style="font-size: 12px">Choose multiple pictures</p>
                    {{ imageform.management_form }}
                    {% for form in imageform %}
                        {{ form }}
                    {% endfor %} 
                    <input type="submit" name="submit" value="Submit" class="button is-success" />
                </form>
            </div>
        </div>
    {% else %}
        <a href="{% url 'login' %}">login</a>or <a href="{% url 'signup' %}">signup</a>
    {% endif %}

{% endblock %}